name: Playwright Tests

on:
  pull_request:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  test:
    name: Playwright end-to-end tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install --no-fund --no-audit --ignore-scripts

      - name: Install Playwright Browsers
        run: npx playwright install chromium --no-shell

      - name: Run Playwright tests
        run: npx playwright test --forbid-only

      - name: Store Playwright test results
        uses: actions/upload-artifact@v5
        with:
          name: css-coverage
          path: css-coverage/*.json
          retention-days: 30

  css-coverage:
    name: Verify CSS Code Coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install --no-fund --no-audit --ignore-scripts

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: css-coverage
          path: ./css-coverage

      - name: Analyze CSS Code Coverage
        run: npm run css-coverage
        env:
          FORCE_COLOR: '3'
